namespace xofz
{
    // the PasswordHolder in Framework.Access depends on these using default values
    // 0, 1, 2, 3, ...
    public enum AccessLevel
    {
        None,
        Level1,
        Level2,
        Level3,
        Level4,
        Level5,
        Level6,
        Level7,
        Level8,
        Level9,
        Level10,
        Level11,
        Level12,
        Level13,
        Level14,
        Level15,
        Level16,
        Level17,
        Level18,
        Level19,
        Level20,
        Level21,
        Level22,
        Level23,
        Level24,
        Level25,
        Level26,
        Level27,
        Level28,
        Level29,
        Level30,
        Level31,
        Level32,
        Level33,
        Level34,
        Level35,
        Level36,
        Level37,
        Level38,
        Level39,
        Level40
    }
}
